# リモートに置かれた.ymlファイルの設定を使用する
parent_config: https://raw.githubusercontent.com/pommdau/SwiftLint-Config/v1.0.1/ikeh1024-base-swiftlint-config.yml

# 対象のファイル・フォルダ
included:
# デフォルトからフォルダ名を変更していない場合、プロジェクト名と同名のフォルダを指定すればいい
  - {プロジェクト名}

# 対象外のファイル・フォルダ
excluded:
  - Pods
  - Generated

